onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider u_CORTEXM3INTEGRATION
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/ISOLATEn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/RETAINn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/nTRST
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SWDITMS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SWCLKTCK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TDI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/CDBGPWRUPACK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/PORESETn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SYSRESETn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/RSTBYPASS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/CGBYPASS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/FCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TRACECLKIN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/STCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/STCALIB
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/AUXFAULT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/BIGEND
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/INTISR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/INTNMI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HREADYI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HRDATAI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HRESPI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/IFLUSH
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HREADYD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HRDATAD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HRESPD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/EXRESPD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HREADYS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HRDATAS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HRESPS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/EXRESPS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/RXEV
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SLEEPHOLDREQn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/EDBGRQ
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/DBGRESTART
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/FIXMASTERTYPE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/WICENREQ
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TSVALUEB
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/MPUDISABLE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/DBGEN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/NIDEN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/DNOTITRANS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TDO
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/nTDOEN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/CDBGPWRUPREQ
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SWDO
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SWDOEN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/JTAGNSW
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SWV
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TRACECLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TRACEDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHADDR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHTRANS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHSIZE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHBURST
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHPROT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHWDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHWRITE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHRDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHREADY
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTMDHRESP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTRANSI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HSIZEI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HADDRI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HBURSTI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HPROTI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/MEMATTRI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HMASTERD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTRANSD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HSIZED
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HADDRD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HBURSTD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HPROTD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/MEMATTRD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/EXREQD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HWRITED
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HWDATAD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HMASTERS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HTRANSS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HWRITES
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HSIZES
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HMASTLOCKS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HADDRS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HWDATAS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HBURSTS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HPROTS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/MEMATTRS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/EXREQS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/BRCHSTAT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/HALTED
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/DBGRESTARTED
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/LOCKUP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SLEEPING
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SLEEPDEEP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SLEEPHOLDACKn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/ETMINTNUM
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/ETMINTSTAT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TRCENA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/CURRPRI
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/SYSRESETREQ
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/TXEV
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/GATEHCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/WICENACK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/WAKEUP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r0_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r1_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r2_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r3_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r4_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r5_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r6_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r7_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r8_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r9_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r10_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r11_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_r12_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_msp_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_psp_o
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_CORTEXM3INTEGRATION/vis_pc_o
add wave -noupdate -divider {Timer 0}
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PCLKG
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PRESETn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PSEL
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PADDR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PENABLE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PWRITE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PWDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PPROT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/ECOREVNUM
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PRDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PREADY
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PSLVERR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/PRIVMODEN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/EXTIN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/TIMERINT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/read_enable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/write_enable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/write_enable00
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/write_enable04
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/write_enable08
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/write_enable0c
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/read_mux_byte0
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/read_mux_byte0_reg
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/read_mux_word
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/pid3_value
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/reg_ctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/reg_curr_val
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/reg_reload_val
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/nxt_curr_val
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/ext_in_sync1
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/ext_in_sync2
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/ext_in_delay
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/ext_in_enable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/dec_ctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/clk_ctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/enable_ctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/edge_detect
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/reg_timer_int
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/timer_int_clear
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/timer_int_set
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_iot_top/u_beid_peripheral_f0/u_p_beid_peripheral_f0_timer0/update_timer_int
add wave -noupdate -divider sysctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HRESETn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/FCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/PORESETn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HSEL
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HREADY
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HTRANS
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HSIZE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HWRITE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HADDR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HWDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/BIGEND
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HREADYOUT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HRESP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HRDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/AHBPER0_REG
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/APBPER0_REG
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/SYSRESETREQ
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/WDOGRESETREQ
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/LOCKUP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ECOREVNUM
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/REMAP
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/PMUENABLE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/LOCKUPRESET
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/read_mux
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/read_mux_le
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_remap
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_pmuenable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_lockupreset
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_resetinfo
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/bigendian
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ahb_access
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ahb_write
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ahb_read
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/nxt_byte_strobe
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_byte_strobe
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_read_enable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_write_enable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_addr
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_hsize
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HWDATALE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_remap_write
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_pmuenable_write
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_lockupreset_write
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_resetinfo_write
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/nxt_resetinfo
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_resetinfo_en
add wave -noupdate -divider sysctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/PMUENABLE
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2650829522 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 234
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2648100096 ps} {2653659904 ps}
