onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PCLK
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PRESETn
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PENABLE
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PSEL
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PADDR
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PWRITE
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PWDATA
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/PRDATA
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/WDOGCLK
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/WDOGCLKEN
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/WDOGRESn
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/ECOREVNUM
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/WDOGINT
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/WDOGRES
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/frc_sel
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/frc_data
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_pdata
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/prdata_next
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/i_prdata
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/prdata_next_en
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_itcr_wr_en
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_itcr
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_itop_wr_en
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_itop
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_lock_wr_en
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_lock_wr_val
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/wdog_lock
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/i_wdogint
add wave -noupdate -group u_cmsdk_apb_watchdog /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/i_wdogres
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/PCLK
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/PRESETn
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/PENABLE
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/PADDR
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/PWRITE
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/PWDATA
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/frc_sel
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_lock
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/WDOGCLK
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/WDOGCLKEN
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/WDOGRESn
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/WDOGINT
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/WDOGRES
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/frc_data
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_ctrl_en
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_control
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/load_en
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/load_en_reg
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_load
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/load_tog_en
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/load_req_tog_p
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/load_req_tog_w
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/load_req_w
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/count_stop
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/count_stop_reg
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_count_low
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_count_high
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_carry_0
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_carry_1
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_carry_mux
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/reg_carry
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/carry_msb
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/count_mux1
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/count_mux2
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/reg_count
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/count_read
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/high_count
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_int_en
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_int_en_reg
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_int_en_rise
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_res_en
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/i_wdog_res
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_wdog_res
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/int_clr_en
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/int_clr_tog_p
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/int_clr_tog_w
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/int_clr_pulse
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/int_clr_w
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/int_clr_reg_w
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/nxt_wdog_ris
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_ris
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/read_wdog_ris
add wave -noupdate -group u_cmsdk_apb_watchdog_frc /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_watchdog/u_apb_watchdog_frc/wdog_mis
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HCLK
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HRESETn
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/FCLK
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/PORESETn
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HSEL
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HREADY
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HTRANS
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HSIZE
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HWRITE
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HADDR
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HWDATA
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/BIGEND
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HREADYOUT
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HRESP
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HRDATA
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/AHBPER0_REG
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/APBPER0_REG
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/SYSRESETREQ
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/WDOGRESETREQ
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/LOCKUP
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ECOREVNUM
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/REMAP
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/PMUENABLE
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/LOCKUPRESET
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/read_mux
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/read_mux_le
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_remap
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_pmuenable
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_lockupreset
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_resetinfo
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/bigendian
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ahb_access
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ahb_write
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/ahb_read
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/nxt_byte_strobe
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_byte_strobe
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_read_enable
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_write_enable
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_addr
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_hsize
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/HWDATALE
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_remap_write
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_pmuenable_write
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_lockupreset_write
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_resetinfo_write
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/nxt_resetinfo
add wave -noupdate -group u_beetle_sysctrl /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_beetle_sysctrl/reg_resetinfo_en
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2459564134 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 165
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {2452747544 ps} {2460863972 ps}
