onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/initexp1_vif/hclk
add wave -noupdate /tb_top/initexp1_vif/hresetn
add wave -noupdate /tb_top/initexp1_vif/HADDR
add wave -noupdate /tb_top/initexp1_vif/HWRITE
add wave -noupdate /tb_top/initexp1_vif/HTRANS
add wave -noupdate /tb_top/initexp1_vif/HSIZE
add wave -noupdate /tb_top/initexp1_vif/HBURST
add wave -noupdate /tb_top/initexp1_vif/HPROT
add wave -noupdate /tb_top/initexp1_vif/HWDATA
add wave -noupdate /tb_top/initexp1_vif/HRDATA
add wave -noupdate /tb_top/initexp1_vif/HRESP
add wave -noupdate /tb_top/initexp1_vif/HSEL
add wave -noupdate /tb_top/initexp1_vif/HREADY
add wave -noupdate -expand -label {Contributors: HREADY} -group {Contributors: sim:/tb_top/initexp1_vif/HREADY} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/data_valid
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/resp_ip
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/data_out_port
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec0
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec1
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec2
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec3
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec4
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec5
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec6
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec7
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dft_slv
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec6
add wave -noupdate -expand -label {Contributors: readyout_dec6} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec6} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm
add wave -noupdate -expand -label {Contributors: i_hreadymuxm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/HREADYOUTM
add wave -noupdate -expand -label {Contributors: i_hreadymuxm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/HCLK
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/HRESETn
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/addr_in_port
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/addr_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/addr_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/addr_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/auser_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/auser_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/auser_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/burst_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/burst_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/burst_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/master_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/master_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/master_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/mastlock_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/mastlock_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/mastlock_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/no_port
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/prot_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/prot_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/prot_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/sel_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/sel_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/sel_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/size_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/size_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/size_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/trans_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/trans_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/trans_op3
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/write_op1
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/write_op2
add wave -noupdate -expand -label {Contributors: i_hselm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/write_op3
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 216
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {959 ps}
