onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/initexp1_vif/hclk
add wave -noupdate /tb_top/initexp1_vif/hresetn
add wave -noupdate /tb_top/initexp1_vif/HADDR
add wave -noupdate /tb_top/initexp1_vif/HWRITE
add wave -noupdate /tb_top/initexp1_vif/HTRANS
add wave -noupdate /tb_top/initexp1_vif/HSIZE
add wave -noupdate /tb_top/initexp1_vif/HBURST
add wave -noupdate /tb_top/initexp1_vif/HPROT
add wave -noupdate /tb_top/initexp1_vif/HWDATA
add wave -noupdate /tb_top/initexp1_vif/HRDATA
add wave -noupdate /tb_top/initexp1_vif/HRESP
add wave -noupdate /tb_top/initexp1_vif/HSEL
add wave -noupdate /tb_top/initexp1_vif/HREADY
add wave -noupdate -expand -label {Contributors: HREADY} -group {Contributors: sim:/tb_top/initexp1_vif/HREADY} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/data_valid
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip
add wave -noupdate -expand -label {Contributors: hreadyoutinitexp1} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/resp_ip
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg
add wave -noupdate -expand -label {Contributors: pend_tran_reg} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/HCLK
add wave -noupdate -expand -label {Contributors: pend_tran_reg} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/HRESETn
add wave -noupdate -expand -label {Contributors: pend_tran_reg} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran
add wave -noupdate -expand -label {Contributors: pend_tran} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/active_ip
add wave -noupdate -expand -label {Contributors: pend_tran} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/load_reg
add wave -noupdate -expand -label {Contributors: pend_tran} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran_reg
add wave -noupdate -expand -label {Contributors: pend_tran} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/pend_tran} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/data_out_port
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec0
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec1
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec2
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec3
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec4
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec5
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec6
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec7
add wave -noupdate -expand -label {Contributors: readyout_ip} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_input_stage_3/readyout_ip} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dft_slv
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec6
add wave -noupdate -expand -label {Contributors: readyout_dec6} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/readyout_dec6} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm
add wave -noupdate -expand -label {Contributors: i_hreadymuxm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/HREADYOUTM
add wave -noupdate -expand -label {Contributors: i_hreadymuxm} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/HCLK
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/HRESETn
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hreadymuxm
add wave -noupdate -expand -label {Contributors: slave_sel} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/slave_sel} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp0_6/i_hselm
add wave -noupdate -divider DUT
add wave -noupdate /tb_top/u_dut/fclk
add wave -noupdate /tb_top/u_dut/cpu0_po_reset_n
add wave -noupdate /tb_top/u_dut/sys_reset_n
add wave -noupdate /tb_top/u_dut/cpu0_sys_reset_n
add wave -noupdate /tb_top/u_dut/cpu0_stclk
add wave -noupdate /tb_top/u_dut/cpu0_stcalib
add wave -noupdate /tb_top/u_dut/cpu0_bigend
add wave -noupdate /tb_top/u_dut/cpu0_dbgen
add wave -noupdate /tb_top/u_dut/cpu0_niden
add wave -noupdate /tb_top/u_dut/cpu0_fixmastertype
add wave -noupdate /tb_top/u_dut/cpu0_isolaten
add wave -noupdate /tb_top/u_dut/cpu0_retainn
add wave -noupdate /tb_top/u_dut/cpu0_mpudisable
add wave -noupdate /tb_top/u_dut/cpu0_sleepholdreqn
add wave -noupdate /tb_top/u_dut/cpu0_rxev
add wave -noupdate /tb_top/u_dut/cpu0_edbgrq
add wave -noupdate /tb_top/u_dut/cpu0_dbgrestart
add wave -noupdate /tb_top/u_dut/cpu0_auxfault
add wave -noupdate /tb_top/u_dut/cpu0_wicenreq
add wave -noupdate /tb_top/u_dut/cpu0_cdbgpwrupreq
add wave -noupdate /tb_top/u_dut/cpu0_sysresetreq
add wave -noupdate /tb_top/u_dut/cpu0_lockup
add wave -noupdate /tb_top/u_dut/wdog_reset_req
add wave -noupdate /tb_top/u_dut/mtx_remap
add wave -noupdate /tb_top/u_dut/cpu0_intisr
add wave -noupdate /tb_top/u_dut/cpu0_intnmi
add wave -noupdate /tb_top/u_dut/sram0_rdata
add wave -noupdate /tb_top/u_dut/sram0_addr
add wave -noupdate /tb_top/u_dut/sram0_wren
add wave -noupdate /tb_top/u_dut/sram0_wdata
add wave -noupdate /tb_top/u_dut/sram0_cs
add wave -noupdate /tb_top/u_dut/sram1_rdata
add wave -noupdate /tb_top/u_dut/sram1_addr
add wave -noupdate /tb_top/u_dut/sram1_wren
add wave -noupdate /tb_top/u_dut/sram1_wdata
add wave -noupdate /tb_top/u_dut/sram1_cs
add wave -noupdate /tb_top/u_dut/sram2_rdata
add wave -noupdate /tb_top/u_dut/sram2_addr
add wave -noupdate /tb_top/u_dut/sram2_wren
add wave -noupdate /tb_top/u_dut/sram2_wdata
add wave -noupdate /tb_top/u_dut/sram2_cs
add wave -noupdate /tb_top/u_dut/sram3_rdata
add wave -noupdate /tb_top/u_dut/sram3_addr
add wave -noupdate /tb_top/u_dut/sram3_wren
add wave -noupdate /tb_top/u_dut/sram3_wdata
add wave -noupdate /tb_top/u_dut/sram3_cs
add wave -noupdate /tb_top/u_dut/targexp0hsel
add wave -noupdate /tb_top/u_dut/targexp0haddr
add wave -noupdate /tb_top/u_dut/targexp0htrans
add wave -noupdate /tb_top/u_dut/targexp0hwrite
add wave -noupdate /tb_top/u_dut/targexp0hsize
add wave -noupdate /tb_top/u_dut/targexp0hburst
add wave -noupdate /tb_top/u_dut/targexp0hprot
add wave -noupdate /tb_top/u_dut/targexp0memattr
add wave -noupdate /tb_top/u_dut/targexp0exreq
add wave -noupdate /tb_top/u_dut/targexp0hmaster
add wave -noupdate /tb_top/u_dut/targexp0hwdata
add wave -noupdate /tb_top/u_dut/targexp0hmastlock
add wave -noupdate /tb_top/u_dut/targexp0hreadymux
add wave -noupdate /tb_top/u_dut/targexp0hauser
add wave -noupdate /tb_top/u_dut/targexp0hwuser
add wave -noupdate /tb_top/u_dut/targexp0hrdata
add wave -noupdate /tb_top/u_dut/targexp0hreadyout
add wave -noupdate /tb_top/u_dut/targexp0hresp
add wave -noupdate /tb_top/u_dut/targexp0exresp
add wave -noupdate /tb_top/u_dut/targexp0hruser
add wave -noupdate /tb_top/u_dut/targexp1hsel
add wave -noupdate /tb_top/u_dut/targexp1haddr
add wave -noupdate /tb_top/u_dut/targexp1htrans
add wave -noupdate /tb_top/u_dut/targexp1hwrite
add wave -noupdate /tb_top/u_dut/targexp1hsize
add wave -noupdate /tb_top/u_dut/targexp1hburst
add wave -noupdate /tb_top/u_dut/targexp1hprot
add wave -noupdate /tb_top/u_dut/targexp1memattr
add wave -noupdate /tb_top/u_dut/targexp1exreq
add wave -noupdate /tb_top/u_dut/targexp1hmaster
add wave -noupdate /tb_top/u_dut/targexp1hwdata
add wave -noupdate /tb_top/u_dut/targexp1hmastlock
add wave -noupdate /tb_top/u_dut/targexp1hreadymux
add wave -noupdate /tb_top/u_dut/targexp1hauser
add wave -noupdate /tb_top/u_dut/targexp1hwuser
add wave -noupdate /tb_top/u_dut/targexp1hrdata
add wave -noupdate /tb_top/u_dut/targexp1hreadyout
add wave -noupdate /tb_top/u_dut/targexp1hresp
add wave -noupdate /tb_top/u_dut/targexp1exresp
add wave -noupdate /tb_top/u_dut/targexp1hruser
add wave -noupdate /tb_top/u_dut/initexp0hsel
add wave -noupdate /tb_top/u_dut/initexp0haddr
add wave -noupdate /tb_top/u_dut/initexp0htrans
add wave -noupdate /tb_top/u_dut/initexp0hwrite
add wave -noupdate /tb_top/u_dut/initexp0hsize
add wave -noupdate /tb_top/u_dut/initexp0hburst
add wave -noupdate /tb_top/u_dut/initexp0hprot
add wave -noupdate /tb_top/u_dut/initexp0memattr
add wave -noupdate /tb_top/u_dut/initexp0exreq
add wave -noupdate /tb_top/u_dut/initexp0hmaster
add wave -noupdate /tb_top/u_dut/initexp0hauser
add wave -noupdate /tb_top/u_dut/initexp0hwuser
add wave -noupdate /tb_top/u_dut/initexp0exresp
add wave -noupdate /tb_top/u_dut/initexp0hruser
add wave -noupdate /tb_top/u_dut/initexp0hmastlock
add wave -noupdate /tb_top/u_dut/initexp0hrdata
add wave -noupdate /tb_top/u_dut/initexp0hready
add wave -noupdate /tb_top/u_dut/initexp0hresp
add wave -noupdate /tb_top/u_dut/initexp0hwdata
add wave -noupdate /tb_top/u_dut/initexp1hsel
add wave -noupdate /tb_top/u_dut/initexp1haddr
add wave -noupdate /tb_top/u_dut/initexp1htrans
add wave -noupdate /tb_top/u_dut/initexp1hwrite
add wave -noupdate /tb_top/u_dut/initexp1hsize
add wave -noupdate /tb_top/u_dut/initexp1hburst
add wave -noupdate /tb_top/u_dut/initexp1hwdata
add wave -noupdate /tb_top/u_dut/initexp1hprot
add wave -noupdate /tb_top/u_dut/initexp1memattr
add wave -noupdate /tb_top/u_dut/initexp1exreq
add wave -noupdate /tb_top/u_dut/initexp1hmaster
add wave -noupdate /tb_top/u_dut/initexp1hauser
add wave -noupdate /tb_top/u_dut/initexp1hwuser
add wave -noupdate /tb_top/u_dut/initexp1exresp
add wave -noupdate /tb_top/u_dut/initexp1hruser
add wave -noupdate /tb_top/u_dut/initexp1hmastlock
add wave -noupdate /tb_top/u_dut/initexp1hrdata
add wave -noupdate /tb_top/u_dut/initexp1hready
add wave -noupdate -expand -label {Contributors: initexp1hready} -group {Contributors: sim:/tb_top/u_dut/initexp1hready} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/hreadyoutinitexp1
add wave -noupdate /tb_top/u_dut/initexp1hresp
add wave -noupdate /tb_top/u_dut/apbtargexp2psel
add wave -noupdate /tb_top/u_dut/apbtargexp2penable
add wave -noupdate /tb_top/u_dut/apbtargexp2paddr
add wave -noupdate /tb_top/u_dut/apbtargexp2pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp2pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp2prdata
add wave -noupdate /tb_top/u_dut/apbtargexp2pready
add wave -noupdate /tb_top/u_dut/apbtargexp2pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp2pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp2pprot
add wave -noupdate /tb_top/u_dut/apbtargexp3psel
add wave -noupdate /tb_top/u_dut/apbtargexp3penable
add wave -noupdate /tb_top/u_dut/apbtargexp3paddr
add wave -noupdate /tb_top/u_dut/apbtargexp3pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp3pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp3prdata
add wave -noupdate /tb_top/u_dut/apbtargexp3pready
add wave -noupdate /tb_top/u_dut/apbtargexp3pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp3pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp3pprot
add wave -noupdate /tb_top/u_dut/apbtargexp4psel
add wave -noupdate /tb_top/u_dut/apbtargexp4penable
add wave -noupdate /tb_top/u_dut/apbtargexp4paddr
add wave -noupdate /tb_top/u_dut/apbtargexp4pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp4pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp4prdata
add wave -noupdate /tb_top/u_dut/apbtargexp4pready
add wave -noupdate /tb_top/u_dut/apbtargexp4pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp4pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp4pprot
add wave -noupdate /tb_top/u_dut/apbtargexp5psel
add wave -noupdate /tb_top/u_dut/apbtargexp5penable
add wave -noupdate /tb_top/u_dut/apbtargexp5paddr
add wave -noupdate /tb_top/u_dut/apbtargexp5pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp5pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp5prdata
add wave -noupdate /tb_top/u_dut/apbtargexp5pready
add wave -noupdate /tb_top/u_dut/apbtargexp5pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp5pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp5pprot
add wave -noupdate /tb_top/u_dut/apbtargexp6psel
add wave -noupdate /tb_top/u_dut/apbtargexp6penable
add wave -noupdate /tb_top/u_dut/apbtargexp6paddr
add wave -noupdate /tb_top/u_dut/apbtargexp6pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp6pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp6prdata
add wave -noupdate /tb_top/u_dut/apbtargexp6pready
add wave -noupdate /tb_top/u_dut/apbtargexp6pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp6pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp6pprot
add wave -noupdate /tb_top/u_dut/apbtargexp7psel
add wave -noupdate /tb_top/u_dut/apbtargexp7penable
add wave -noupdate /tb_top/u_dut/apbtargexp7paddr
add wave -noupdate /tb_top/u_dut/apbtargexp7pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp7pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp7prdata
add wave -noupdate /tb_top/u_dut/apbtargexp7pready
add wave -noupdate /tb_top/u_dut/apbtargexp7pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp7pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp7pprot
add wave -noupdate /tb_top/u_dut/apbtargexp8psel
add wave -noupdate /tb_top/u_dut/apbtargexp8penable
add wave -noupdate /tb_top/u_dut/apbtargexp8paddr
add wave -noupdate /tb_top/u_dut/apbtargexp8pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp8pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp8prdata
add wave -noupdate /tb_top/u_dut/apbtargexp8pready
add wave -noupdate /tb_top/u_dut/apbtargexp8pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp8pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp8pprot
add wave -noupdate /tb_top/u_dut/apbtargexp9psel
add wave -noupdate /tb_top/u_dut/apbtargexp9penable
add wave -noupdate /tb_top/u_dut/apbtargexp9paddr
add wave -noupdate /tb_top/u_dut/apbtargexp9pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp9pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp9prdata
add wave -noupdate /tb_top/u_dut/apbtargexp9pready
add wave -noupdate /tb_top/u_dut/apbtargexp9pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp9pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp9pprot
add wave -noupdate /tb_top/u_dut/apbtargexp10psel
add wave -noupdate /tb_top/u_dut/apbtargexp10penable
add wave -noupdate /tb_top/u_dut/apbtargexp10paddr
add wave -noupdate /tb_top/u_dut/apbtargexp10pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp10pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp10prdata
add wave -noupdate /tb_top/u_dut/apbtargexp10pready
add wave -noupdate /tb_top/u_dut/apbtargexp10pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp10pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp10pprot
add wave -noupdate /tb_top/u_dut/apbtargexp11psel
add wave -noupdate /tb_top/u_dut/apbtargexp11penable
add wave -noupdate /tb_top/u_dut/apbtargexp11paddr
add wave -noupdate /tb_top/u_dut/apbtargexp11pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp11pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp11prdata
add wave -noupdate /tb_top/u_dut/apbtargexp11pready
add wave -noupdate /tb_top/u_dut/apbtargexp11pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp11pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp11pprot
add wave -noupdate /tb_top/u_dut/apbtargexp12psel
add wave -noupdate /tb_top/u_dut/apbtargexp12penable
add wave -noupdate /tb_top/u_dut/apbtargexp12paddr
add wave -noupdate /tb_top/u_dut/apbtargexp12pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp12pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp12prdata
add wave -noupdate /tb_top/u_dut/apbtargexp12pready
add wave -noupdate /tb_top/u_dut/apbtargexp12pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp12pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp12pprot
add wave -noupdate /tb_top/u_dut/apbtargexp13psel
add wave -noupdate /tb_top/u_dut/apbtargexp13penable
add wave -noupdate /tb_top/u_dut/apbtargexp13paddr
add wave -noupdate /tb_top/u_dut/apbtargexp13pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp13pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp13prdata
add wave -noupdate /tb_top/u_dut/apbtargexp13pready
add wave -noupdate /tb_top/u_dut/apbtargexp13pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp13pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp13pprot
add wave -noupdate /tb_top/u_dut/apbtargexp14psel
add wave -noupdate /tb_top/u_dut/apbtargexp14penable
add wave -noupdate /tb_top/u_dut/apbtargexp14paddr
add wave -noupdate /tb_top/u_dut/apbtargexp14pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp14pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp14prdata
add wave -noupdate /tb_top/u_dut/apbtargexp14pready
add wave -noupdate /tb_top/u_dut/apbtargexp14pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp14pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp14pprot
add wave -noupdate /tb_top/u_dut/apbtargexp15psel
add wave -noupdate /tb_top/u_dut/apbtargexp15penable
add wave -noupdate /tb_top/u_dut/apbtargexp15paddr
add wave -noupdate /tb_top/u_dut/apbtargexp15pwrite
add wave -noupdate /tb_top/u_dut/apbtargexp15pwdata
add wave -noupdate /tb_top/u_dut/apbtargexp15prdata
add wave -noupdate /tb_top/u_dut/apbtargexp15pready
add wave -noupdate /tb_top/u_dut/apbtargexp15pslverr
add wave -noupdate /tb_top/u_dut/apbtargexp15pstrb
add wave -noupdate /tb_top/u_dut/apbtargexp15pprot
add wave -noupdate /tb_top/u_dut/nTRST
add wave -noupdate /tb_top/u_dut/SWCLKTCK
add wave -noupdate /tb_top/u_dut/SWDITMS
add wave -noupdate /tb_top/u_dut/TDI
add wave -noupdate /tb_top/u_dut/TDO
add wave -noupdate /tb_top/u_dut/nTDOEN
add wave -noupdate /tb_top/u_dut/SWDO
add wave -noupdate /tb_top/u_dut/SWDOEN
add wave -noupdate /tb_top/u_dut/JTAGNSW
add wave -noupdate /tb_top/u_dut/SWV
add wave -noupdate /tb_top/u_dut/TRACECLK
add wave -noupdate /tb_top/u_dut/TRACEDATA
add wave -noupdate /tb_top/u_dut/trcena
add wave -noupdate /tb_top/u_dut/cpu0tsvalueb
add wave -noupdate /tb_top/u_dut/cpu0halted
add wave -noupdate /tb_top/u_dut/cpu0wakeup
add wave -noupdate /tb_top/u_dut/cpu0wicenack
add wave -noupdate /tb_top/u_dut/cpu0wicsense
add wave -noupdate /tb_top/u_dut/cpu0cdbgpwrupack
add wave -noupdate /tb_top/u_dut/flash_err_o
add wave -noupdate /tb_top/u_dut/flash_int_o
add wave -noupdate /tb_top/u_dut/dftscanmode
add wave -noupdate /tb_top/u_dut/dftcgen
add wave -noupdate /tb_top/u_dut/dftse
add wave -noupdate /tb_top/u_dut/targflash0hsel
add wave -noupdate /tb_top/u_dut/targflash0haddr
add wave -noupdate /tb_top/u_dut/targflash0htrans
add wave -noupdate /tb_top/u_dut/targflash0hwrite
add wave -noupdate /tb_top/u_dut/targflash0hsize
add wave -noupdate /tb_top/u_dut/targflash0hwdata
add wave -noupdate /tb_top/u_dut/targflash0hburst
add wave -noupdate /tb_top/u_dut/targflash0hprot
add wave -noupdate /tb_top/u_dut/targflash0memattr
add wave -noupdate /tb_top/u_dut/targflash0exreq
add wave -noupdate /tb_top/u_dut/targflash0hmaster
add wave -noupdate /tb_top/u_dut/targflash0hmastlock
add wave -noupdate /tb_top/u_dut/targflash0hauser
add wave -noupdate /tb_top/u_dut/targflash0hwuser
add wave -noupdate /tb_top/u_dut/targflash0hreadymux
add wave -noupdate /tb_top/u_dut/targflash0hreadyout
add wave -noupdate /tb_top/u_dut/targflash0hrdata
add wave -noupdate /tb_top/u_dut/targflash0hresp
add wave -noupdate /tb_top/u_dut/targflash0exresp
add wave -noupdate /tb_top/u_dut/targflash0hruser
add wave -noupdate /tb_top/u_dut/SRAMFHCLK
add wave -noupdate /tb_top/u_dut/SRAM0HCLK
add wave -noupdate /tb_top/u_dut/SRAM1HCLK
add wave -noupdate /tb_top/u_dut/SRAM2HCLK
add wave -noupdate /tb_top/u_dut/SRAM3HCLK
add wave -noupdate /tb_top/u_dut/MTXHCLK
add wave -noupdate /tb_top/u_dut/AHB2APBHCLK
add wave -noupdate /tb_top/u_dut/TIMER0PCLK
add wave -noupdate /tb_top/u_dut/TIMER0PCLKG
add wave -noupdate /tb_top/u_dut/TIMER1PCLK
add wave -noupdate /tb_top/u_dut/TIMER1PCLKG
add wave -noupdate /tb_top/u_dut/CPU0FCLK
add wave -noupdate /tb_top/u_dut/CPU0HCLK
add wave -noupdate /tb_top/u_dut/TPIUTRACECLKIN
add wave -noupdate /tb_top/u_dut/PCLK
add wave -noupdate /tb_top/u_dut/PCLKG
add wave -noupdate /tb_top/u_dut/MTXHRESETn
add wave -noupdate /tb_top/u_dut/SRAMHRESETn
add wave -noupdate /tb_top/u_dut/TIMER0PRESETn
add wave -noupdate /tb_top/u_dut/TIMER1PRESETn
add wave -noupdate -divider Targexp1
add wave -noupdate /tb_top/targexp1_vif/hclk
add wave -noupdate /tb_top/targexp1_vif/hresetn
add wave -noupdate /tb_top/targexp1_vif/HADDR
add wave -noupdate /tb_top/targexp1_vif/HWRITE
add wave -noupdate /tb_top/targexp1_vif/HTRANS
add wave -noupdate /tb_top/targexp1_vif/HSIZE
add wave -noupdate /tb_top/targexp1_vif/HBURST
add wave -noupdate /tb_top/targexp1_vif/HPROT
add wave -noupdate /tb_top/targexp1_vif/HWDATA
add wave -noupdate /tb_top/targexp1_vif/HRDATA
add wave -noupdate /tb_top/targexp1_vif/HREADYOUT
add wave -noupdate /tb_top/targexp1_vif/HRESP
add wave -noupdate /tb_top/targexp1_vif/HSEL
add wave -noupdate /tb_top/targexp1_vif/HREADYMUX
add wave -noupdate /tb_top/targexp1_vif/HREADY
add wave -noupdate -expand /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/addr_out_port
add wave -noupdate /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/active_dec7
add wave -noupdate -expand -label {Contributors: active_dec7} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/active_dec7} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp1_7/addr_in_port
add wave -noupdate -expand -label {Contributors: active_dec7} -group {Contributors: sim:/tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_decoderinitexp1/active_dec7} /tb_top/u_dut/u_iot_top/u_p_beid_interconnect_f0/u_p_beid_interconnect_f0_ahb_mtx/u_p_beid_interconnect_f0_ahb_mtx_output_stagetargexp1_7/no_port
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {105000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 216
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1160250 ps}
